### ISSUE TITLE
Read underflow when retrieving topic metadata

### ISSUE THREAD

**Issue by dstelljes** [confluentinc/librdkafka#4253]
Description
===========

Starting in 2.1.0, some topic metadata requests fail with PROTOUFLOW:

```
%3|1681391022.842|PROTOUFLOW|rdkafka#producer-1| [thrd:main]: sasl_plaintext://bootstrap.redacted.net:9092/bootstrap: Protocol read buffer underflow for Metadata v9 at 629/631 (rd_kafka_parse_Metadata:470): expected 4 bytes > 2 remaining bytes (incorrect broker.version.fallback?)
%4|1681391022.842|METADATA|rdkafka#producer-1| [thrd:main]: sasl_plaintext://bootstrap.redacted.net:9092/bootstrap: Metadata request failed: connected: Local: Read underflow (67ms): Permanent
%3|1681391022.909|PROTOUFLOW|rdkafka#producer-1| [thrd:main]: sasl_plaintext://bootstrap.redacted.net:9092/bootstrap: Protocol read buffer underflow for Metadata v9 at 629/631 (rd_kafka_parse_Metadata:470): expected 4 bytes > 2 remaining bytes (incorrect broker.version.fallback?)
%4|1681391022.909|METADATA|rdkafka#producer-1| [thrd:main]: sasl_plaintext://bootstrap.redacted.net:9092/bootstrap: Metadata request failed: application requested: Local: Read underflow (134ms): Permanent
```

In testing, it seems like the issue is more likely to happen for topics with longer names. Security protocol does not appear to be a factor.

The issue is not reproducible on 2.0.2.

How to reproduce
================

With confluent-kafka-dotnet 2.1.0:

```csharp
using Confluent.Kafka;

const string BootstrapServers = "bootstrap.redacted.net:9092";
const string Topic = "a-thirty-four-character-topic-name";

using var admin = new AdminClientBuilder(
    new AdminClientConfig {
        BootstrapServers = BootstrapServers,
    })
    .Build();

var metadata = admin.GetMetadata(Topic, TimeSpan.FromSeconds(30));
Console.WriteLine(string.Join(Environment.NewLine, metadata.Topics.Select(t => t.Topic)));
```

```
Unhandled exception. Confluent.Kafka.KafkaException: Local: Read underflow
   at Confluent.Kafka.Impl.SafeKafkaHandle.GetMetadata(Boolean allTopics, SafeTopicHandle topic, Int32 millisecondsTimeout)
   at Confluent.Kafka.AdminClient.GetMetadata(String topic, TimeSpan timeout)
   at Program.<Main>$(String[] args) in /path/to/kafka-underflow-repro/dotnet/Program.cs:line 20
```

With confluent-kafka-go 2.1.0:

```go
package main

import (
	"fmt"
	"os"

	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
)

const (
	bootstrapServers = "bootstrap.redacted.net:9092"
)

func main() {
	topic := "a-thirty-four-character-topic-name"

	a, err := kafka.NewAdminClient(&kafka.ConfigMap{
		"bootstrap.servers": bootstrapServers,
	})
	if err != nil {
		fmt.Printf("Failed to create admin client: %s\n", err)
		os.Exit(1)
	}

	metadata, err := a.GetMetadata(&topic, false, 30000)
	if err != nil {
		fmt.Printf("Failed to get topic metadata: %s\n", err)
		os.Exit(1)
	}
	_ = metadata
}
```

```
Failed to get topic metadata: Local: Read underflow
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 2.1.0
 - [x] Apache Kafka version: 3.3.1
 - [x] librdkafka client configuration: `bootstrap.servers=redacted.example.net:9092`
 - [x] Operating system: macOS 13.3.1 (ARM), Windows 10 (x64)
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: [dotnet.log](https://github.com/confluentinc/librdkafka/files/11222710/dotnet.log), [go.log](https://github.com/confluentinc/librdkafka/files/11222712/go.log)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
Hello I think it's related to the upgrade to flexver, in particular the last tags read that is duplicate. Unfortunately, I cannot reproduce it even with a topic eight times longer than this, on Linux. Have to try a way for testing the fix.
I've put my changes here for the moment https://github.com/confluentinc/librdkafka/tree/dev_fix_duplicate_skip_tags

**Comment by dstelljes** [comment]
Thanks @emasab; I’ll try to figure out a totally standalone reproduction. There are 8 brokers in the internal cluster that this was reported on. The topics are each configured with a replication factor of 6 and have 3 ISRs.

I tested your fix with confluent-kafka-go and got the same error.

**Comment by dstelljes** [comment]
@emasab I was finally able to reproduce this against a synthetic cluster. For whatever this is worth, I could only get the issue to occur when the `confluent.placement.constraints` config was set on the topic and partition count was greater than 1.

docker-compose.yml:

```yaml
---
version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: WARN
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    image: confluentinc/cp-server:7.3.3
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9091
      KAFKA_BROKER_ID: '101'
      KAFKA_BROKER_RACK: az-1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9091:9091

  broker-2:
    image: confluentinc/cp-server:7.3.3
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_BROKER_ID: '102'
      KAFKA_BROKER_RACK: az-1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092

  broker-3:
    image: confluentinc/cp-server:7.3.3
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-3:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_BROKER_ID: '113'
      KAFKA_BROKER_RACK: az-2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9093:9093
```

placement.json:

```json
{
    "observerPromotionPolicy": "under-min-isr",
    "version": 2,
    "replicas": [
        {
            "count": 2,
            "constraints": {
                "rack": "az-1"
            }
        }
    ],
    "observers": [
        {
            "count": 1,
            "constraints": {
                "rack": "az-2"
            }
        }
    ]
}
```

Setup steps:

```sh
kafka-topics --bootstrap-server localhost:9091 --create --partitions 2 --replica-placement placement.json --topic underflow-repro-2-partitions-placement-constraints
```

Reproduction code (C#):

```csharp
using System.Text.Json;
using Confluent.Kafka;

const string BootstrapServers = "localhost:9091";
const string Topic = "underflow-repro-2-partitions-placement-constraints";

using var admin = new AdminClientBuilder(
    new AdminClientConfig {
        BootstrapServers = BootstrapServers,
    })
    .Build();

var metadata = admin.GetMetadata(Topic, TimeSpan.FromSeconds(30));
Console.WriteLine(JsonSerializer.Serialize(metadata, options: new JsonSerializerOptions
{
    WriteIndented = true,
}));
```
